config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  # This route no longer exists: get 'home/index'
  root 'home#index'
  get 'home/about'
  post "/" => 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'stock_quote'
  def index
    if params[:ticker] == ""
      @nothing = "You forgot to enter a symbol"
    elsif params[:ticker]
    StockQuote::Stock.new(api_key: 'sk_c21a00c6fe03437481d9371e280d2c04')
      begin
      @stock = StockQuote::Stock.quote(params[:ticker])
      rescue RuntimeError => e
      @error = "There was an Error retrieving stock data: #{e.message}"
      end
    end
  end

  def about
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @ticker = current_user.stocks.find_by(id: params[:id])
    redirect_to stocks_path, notice: "Not Authorized to edit this stock" if @ticker.nil?

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<br>
<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/home/_footer.html.erb
<br><br><br><br><br>
<center>Copyright (c) Marilyn Marquez 2023</center>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Stocky", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
       <%= link_to "About", home_about_path, class: "nav-link text-light" %>
      </li>

      <% if user_signed_in? %>
       <li class="nav-item">
       <%= link_to "Edit Profile",  edit_user_registration_path, class: "nav-link text-light" %>
      </li>
      <li class="nav-item">
       <%= link_to "Show Stocks",  stocks_path, class: "nav-link text-light" %>
      </li>
      <li class="nav-item">
       <%= link_to "Add Stock",  new_stock_path, class: "nav-link text-light" %>
      </li>
      <li class="nav-item">
       <%= button_to "Logout", destroy_user_session_path,  method: :delete, class: "btn btn-dark text-light" %>
      </li>
      <% else %>
      <li class="nav-item">
       <%= link_to "Login", new_user_session_path, class: "nav-link text-light" %>
      </li>
       <li class="nav-item">
       <%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-light" %>
      </li>
      <% end %>
      
       
       
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>    

    
    
    
    
    

app/views/home/about.html.erb
<h1>ABOUT</h1>
<p>Hello, this is my About page</p>

app/views/home/index.html.erb
<h1>Stocky</h1>
<p>A friendly and easy-to-use app to keep track of your stock portfolio</p>

<%= form_tag root_path :method => 'POST' do %>
    <%= text_field_tag 'ticker', nil, placeholder: "Enter ticker symbol", data: {turbo:"false"}  %>
    <%= submit_tag 'Lookup', data: {turbo:"false"}  %>
<% end %>

<br>
<% if @error %>
  <%= @error %>
<% elsif @stock %>
    <%= @stock.symbol %> <br>
    <%= @stock.company_name %> <br>
    Latest Price: $<%= @stock.latest_price %> <br>
    Previous Close: $<%= @stock.previous_close %> <br>
    Primary Exchange: <%= @stock.primary_exchange%>

<% elsif @nothing %>
    <%= @nothing %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Stocks App</title>
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  

  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
    <%= render 'home/flash' %>
    <br>
    <%= yield %>
    </div>
    
     <%= render 'home/footer' %>

    
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
  <% if stock.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ticker, style: "display: block" %>
    <%= form.text_field :ticker %>
  </div>

  <div>

    <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
    
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
  <p>
    <strong>Ticker:</strong>
    <%= stock.ticker %>
  </p>

  <p>
    <strong>User:</strong>
    <%= stock.user_id %>
  </p>

</div>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Show this stock", @stock %> |
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/index.html.erb
<div class="container">
<h1>Stocks</h1>

<table>
<thead>
  <th>Ticker</th>
  <th>User</th>
  <th colspan="3"></th>
</thead>

<tbody>
   <% @stocks.each do |stock| %>
   <% if stock.user_id == current_user.id %>
  
   <tr>
    <td><%= stock.ticker %></td>
    <td><%= stock.user_id %></td>
    <td><%= link_to "Show", stock %></td>
    <td><%= link_to "Edit", edit_stock_path(stock) %></td>
    <td><%= link_to "Destroy", stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
   </tr>
   <% end %>
   <% end %>
</tbody>
</table>

<%= link_to "New stock", new_stock_path %>
</div>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/show.html.erb
<%# <%= render @stock %>
<strong>Ticker:</strong>
<%= @stock.ticker %>

<div>
  <%= link_to "Edit this stock", edit_stock_path(@stock) %> |
  <%= link_to "Back to stocks", stocks_path %>

  <%= button_to "Destroy this stock", @stock, method: :delete %>
</div>